# This file was generated by GoReleaser. DO NOT EDIT.
cask "tslink" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "25e042c9e392f9125d6db32c73e1365acd17d8f451b122b46bf0f145d2a423ab"
      url "https://github.com/anydoor7/tslink/releases/download/v#{version}/tslink_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfafc6e48c0e86c6808ffe79929743fc6d6f76013cac1dfd6c75605a0d1cad68"
      url "https://github.com/anydoor7/tslink/releases/download/v#{version}/tslink_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af1afbb1278547115ea6dfde61d1d9092b0274c518f8c504ed4a84a257464bd4"
      url "https://github.com/anydoor7/tslink/releases/download/v#{version}/tslink_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4417b87dfdee8d21779ccb85b7e354a3a571ecc30fbc5d3d5ef5486578b81eb5"
      url "https://github.com/anydoor7/tslink/releases/download/v#{version}/tslink_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tslink"
  desc "Give each local app a private Tailscale address and control who can reach it"
  homepage "https://github.com/anydoor7/tslink"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tslink"

  # No zap stanza required

  caveats <<~EOS
    On macOS, tslink is signed with a Developer ID certificate and notarized
    by Apple. The first run needs network access so macOS can look up the
    notarization ticket: a bare binary cannot carry a stapled ticket.
    After brew upgrade, run tslink install again if TSLink runs as a
    background service, so the service starts the upgraded binary.
  EOS
end
