# This file was generated by GoReleaser. DO NOT EDIT.
cask "tslink" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "567446a7dd204b2fbc98df35d29ef7407c2df2a472408f814dd05a9b7e77cf50"
      url "https://github.com/anydoor7/tslink/releases/download/v#{version}/tslink_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5da105974a5dd07126fe13ecf397c704c408063bd706ea11efe81c2d51c4c5b7"
      url "https://github.com/anydoor7/tslink/releases/download/v#{version}/tslink_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bc3d5c70311905d793548d81d86e491d73e4e97294d63238aa36c4453603c5b7"
      url "https://github.com/anydoor7/tslink/releases/download/v#{version}/tslink_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "20cf62869f8312da9a199fe19b6461ea004832bbbdadb72c49ecdaa9d3c64a10"
      url "https://github.com/anydoor7/tslink/releases/download/v#{version}/tslink_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tslink"
  desc "Give each local app a private Tailscale address and control who can reach it"
  homepage "https://github.com/anydoor7/tslink"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tslink"

  # No zap stanza required

  caveats <<~EOS
    On macOS, tslink is signed with a Developer ID certificate and notarized
    by Apple. The first run needs network access so macOS can look up the
    notarization ticket: a bare binary cannot carry a stapled ticket.
    After brew upgrade, run tslink install again if TSLink runs as a
    background service, so the service starts the upgraded binary.
  EOS
end
